# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(default=game.models.gen_game_id, max_length=6, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('code_colour_1', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('code_colour_2', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('code_colour_3', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('code_colour_4', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_colour_1', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('guess_colour_2', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('guess_colour_3', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('guess_colour_4', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('B', 'Black')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
    ]
