# Generated by Django 2.0 on 2017-12-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171231_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code_colour_1',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='code_colour_2',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='code_colour_3',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='code_colour_4',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamerow',
            name='guess_colour_1',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamerow',
            name='guess_colour_2',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamerow',
            name='guess_colour_3',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamerow',
            name='guess_colour_4',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('BU', 'Blue'), ('Y', 'Yellow'), ('W', 'White'), ('BA', 'Black')], max_length=2),
        ),
    ]
